### ISSUE TITLE
查分遇到问题

### ISSUE THREAD

**Issue by WindyPear-Team** [mqnu00/koishi-plugin-phigros#1]
成绩图可以渲染，但是查b19会报错。
command b19 TypeError: Cannot read properties of undefined (reading 'chart') at /root/.koishi/data/instances/default/node_modules/koishi-plugin-phigros-redo/lib/index.js:240:63 at Array.map (<anonymous>) at songRKS (/root/.koishi/data/instances/default/node_modules/koishi-plugin-phigros-redo/lib/index.js:235:17) at /root/.koishi/data/instances/default/node_modules/koishi-plugin-phigros-redo/lib/index.js:247:34 at Array.map (<anonymous>) at best (/root/.koishi/data/instances/default/node_modules/koishi-plugin-phigros-redo/lib/index.js:247:23) at rks (/root/.koishi/data/instances/default/node_modules/koishi-plugin-phigros-redo/lib/index.js:252:16) at _Command.<anonymous> (/root/.koishi/data/instances/default/node_modules/koishi-plugin-phigros-redo/lib/index.js:980:21) at pr

**Comment by mqnu00** [comment]
已更新到v2.0.11，github文件还没上传，有问题继续反馈。
因为我使用的是萌娘百科上收录的曲谱信息，最近新增了两首，作者在百科上有笔误。

**Comment by mqnu00** [comment]
没有其他问题我就关闭issue了的😘
